# Generated by Django 4.2.4 on 2023-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goal_lists", "0003_goalinlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goallist",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Путешествия"),
                    ("fun", "Развлечения"),
                    ("clever", "Развитие"),
                ],
                max_length=50,
            ),
        ),
    ]
