# Generated by Django 4.2.4 on 2023-08-14 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0003_initial"),
        ("goal_lists", "0004_alter_goallist_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="goallist",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="goal_list_comments", to="comments.comment"
            ),
        ),
        migrations.AddField(
            model_name="goallist",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_lists_subcategory",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="goallist",
            name="added_by_users",
            field=models.ManyToManyField(
                blank=True, related_name="added_goal_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="goallist",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
        migrations.AlterField(
            model_name="goallist",
            name="completed_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_goal_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="goallist",
            name="complexity",
            field=models.CharField(
                choices=[("easy", "Легко"), ("medium", "Средне"), ("hard", "Тяжело")],
                max_length=20,
            ),
        ),
    ]
