# Generated by Django 4.2.3 on 2024-01-11 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goal_lists', '0006_remove_goallist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='goallist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
