# Generated by Django 4.2.3 on 2024-01-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_icon'),
        ('goal_lists', '0007_goallist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goallist',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='goallist',
            name='complexity',
            field=models.CharField(blank=True, choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Тяжело')], max_length=20),
        ),
    ]
