# Generated by Django 4.2.3 on 2024-01-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_icon'),
        ('goal_lists', '0009_alter_goallist_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goallist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
