export const countries = {
	AF: {name: 'Афганистан', iso: 'AF'},
	AX: {name: 'Аландские острова', iso: 'AX'},
	AL: {name: 'Албания', iso: 'AL'},
	DZ: {name: 'Алжир', iso: 'DZ'},
	AS: {name: 'Американское Самоа', iso: 'AS'},
	AD: {name: 'Андорра', iso: 'AD'},
	AO: {name: 'Ангола', iso: 'AO'},
	AI: {name: 'Ангилья', iso: 'AI'},
	AQ: {name: 'Антарктика', iso: 'AQ'},
	AG: {name: 'Антигуа и Барбуда', iso: 'AG'},
	AR: {name: 'Аргентина', iso: 'AR'},
	AM: {name: 'Армения', iso: 'AM'},
	AW: {name: 'Аруба', iso: 'AW'},
	AU: {name: 'Австралия', iso: 'AU'},
	AT: {name: 'Австрия', iso: 'AT'},
	AZ: {name: 'Азербайджан', iso: 'AZ'},
	BS: {name: 'Багамы', iso: 'BS'},
	BH: {name: 'Бахрейн', iso: 'BH'},
	BD: {name: 'Бангладеш', iso: 'BD'},
	BB: {name: 'Барбадос', iso: 'BB'},
	BY: {name: 'Беларусь', iso: 'BY'},
	BE: {name: 'Бельгия', iso: 'BE'},
	BZ: {name: 'Белиз', iso: 'BZ'},
	BJ: {name: 'Бенин', iso: 'BJ'},
	BM: {name: 'Бермудские острова', iso: 'BM'},
	BT: {name: 'Бутан', iso: 'BT'},
	BO: {name: 'Боливия', iso: 'BO'},
	BQ: {name: 'Бонэйр, Синт-Эстатиус и Саба', iso: 'BQ'},
	BA: {name: 'Босния и Герцеговина', iso: 'BA'},
	BW: {name: 'Ботсвана', iso: 'BW'},
	BV: {name: 'Буве', iso: 'BV'},
	BR: {name: 'Бразилия', iso: 'BR'},
	IO: {name: 'Британская территория в Индийском океане', iso: 'IO'},
	BN: {name: 'Бруней', iso: 'BN'},
	BG: {name: 'Болгария', iso: 'BG'},
	BF: {name: 'Буркина-Фасо', iso: 'BF'},
	BI: {name: 'Бурунди', iso: 'BI'},
	KH: {name: 'Камбоджа', iso: 'KH'},
	CM: {name: 'Камерун', iso: 'CM'},
	CA: {name: 'Канада', iso: 'CA'},
	CV: {name: 'Кабо-Верде', iso: 'CV'},
	KY: {name: 'Каймановы острова', iso: 'KY'},
	CF: {name: 'Центральноафриканская Республика', iso: 'CF'},
	TD: {name: 'Чад', iso: 'TD'},
	CL: {name: 'Чили', iso: 'CL'},
	CN: {name: 'Китай', iso: 'CN'},
	CX: {name: 'Остров Рождества', iso: 'CX'},
	CC: {name: 'Кокосовые (Килинг) острова', iso: 'CC'},
	CO: {name: 'Колумбия', iso: 'CO'},
	KM: {name: 'Коморы', iso: 'KM'},
	CG: {name: 'Конго', iso: 'CG'},
	CD: {name: 'Конго (Демократическая Республика)', iso: 'CD'},
	CK: {name: 'Острова Кука', iso: 'CK'},
	CR: {name: 'Коста-Рика', iso: 'CR'},
	CI: {name: "Кот-д'Ивуар", iso: 'CI'},
	HR: {name: 'Хорватия', iso: 'HR'},
	CU: {name: 'Куба', iso: 'CU'},
	CW: {name: 'Кюрасао', iso: 'CW'},
	CY: {name: 'Кипр', iso: 'CY'},
	CZ: {name: 'Чехия', iso: 'CZ'},
	DK: {name: 'Дания', iso: 'DK'},
	DJ: {name: 'Джибути', iso: 'DJ'},
	DM: {name: 'Доминика', iso: 'DM'},
	DO: {name: 'Доминиканская Республика', iso: 'DO'},
	EC: {name: 'Эквадор', iso: 'EC'},
	EG: {name: 'Египет', iso: 'EG'},
	SV: {name: 'Сальвадор', iso: 'SV'},
	GQ: {name: 'Экваториальная Гвинея', iso: 'GQ'},
	ER: {name: 'Эритрея', iso: 'ER'},
	EE: {name: 'Эстония', iso: 'EE'},
	ET: {name: 'Эфиопия', iso: 'ET'},
	FK: {name: 'Фолклендские (Мальвинские) острова', iso: 'FK'},
	FO: {name: 'Фарерские острова', iso: 'FO'},
	FJ: {name: 'Фиджи', iso: 'FJ'},
	FI: {name: 'Финляндия', iso: 'FI'},
	FR: {name: 'Франция', iso: 'FR'},
	GF: {name: 'Французская Гвиана', iso: 'GF'},
	PF: {name: 'Французская Полинезия', iso: 'PF'},
	TF: {name: 'Французские Южные территории', iso: 'TF'},
	GA: {name: 'Габон', iso: 'GA'},
	GM: {name: 'Гамбия', iso: 'GM'},
	GE: {name: 'Грузия', iso: 'GE'},
	DE: {name: 'Германия', iso: 'DE'},
	GH: {name: 'Гана', iso: 'GH'},
	GI: {name: 'Гибралтар', iso: 'GI'},
	GR: {name: 'Греция', iso: 'GR'},
	GL: {name: 'Гренландия', iso: 'GL'},
	GD: {name: 'Гренада', iso: 'GD'},
	GP: {name: 'Гваделупа', iso: 'GP'},
	GU: {name: 'Гуам', iso: 'GU'},
	GT: {name: 'Гватемала', iso: 'GT'},
	GG: {name: 'Гернси', iso: 'GG'},
	GN: {name: 'Гвинея', iso: 'GN'},
	GW: {name: 'Гвинея-Бисау', iso: 'GW'},
	GY: {name: 'Гайана', iso: 'GY'},
	HT: {name: 'Гаити', iso: 'HT'},
	HM: {name: 'Остров Херд и острова Макдональд', iso: 'HM'},
	VA: {name: 'Ватикан', iso: 'VA'},
	HN: {name: 'Гондурас', iso: 'HN'},
	HK: {name: 'Гонконг', iso: 'HK'},
	HU: {name: 'Венгрия', iso: 'HU'},
	IS: {name: 'Исландия', iso: 'IS'},
	IN: {name: 'Индия', iso: 'IN'},
	ID: {name: 'Индонезия', iso: 'ID'},
	IR: {name: 'Иран', iso: 'IR'},
	IQ: {name: 'Ирак', iso: 'IQ'},
	IE: {name: 'Ирландия', iso: 'IE'},
	IM: {name: 'Остров Мэн', iso: 'IM'},
	IL: {name: 'Израиль', iso: 'IL'},
	IT: {name: 'Италия', iso: 'IT'},
	JM: {name: 'Ямайка', iso: 'JM'},
	JP: {name: 'Япония', iso: 'JP'},
	JE: {name: 'Джерси', iso: 'JE'},
	JO: {name: 'Иордания', iso: 'JO'},
	KZ: {name: 'Казахстан', iso: 'KZ'},
	KE: {name: 'Кения', iso: 'KE'},
	KI: {name: 'Кирибати', iso: 'KI'},
	KP: {name: 'Северная Корея', iso: 'KP'},
	KR: {name: 'Южная Корея', iso: 'KR'},
	KW: {name: 'Кувейт', iso: 'KW'},
	KG: {name: 'Киргизия', iso: 'KG'},
	LA: {name: 'Лаос', iso: 'LA'},
	LV: {name: 'Латвия', iso: 'LV'},
	LB: {name: 'Ливан', iso: 'LB'},
	LS: {name: 'Лесото', iso: 'LS'},
	LR: {name: 'Либерия', iso: 'LR'},
	LY: {name: 'Ливия', iso: 'LY'},
	LI: {name: 'Лихтенштейн', iso: 'LI'},
	LT: {name: 'Литва', iso: 'LT'},
	LU: {name: 'Люксембург', iso: 'LU'},
	MO: {name: 'Макао', iso: 'MO'},
	MK: {name: 'Македония', iso: 'MK'},
	MG: {name: 'Мадагаскар', iso: 'MG'},
	MW: {name: 'Малави', iso: 'MW'},
	MY: {name: 'Малайзия', iso: 'MY'},
	MV: {name: 'Мальдивы', iso: 'MV'},
	ML: {name: 'Мали', iso: 'ML'},
	MT: {name: 'Мальта', iso: 'MT'},
	MH: {name: 'Маршалловы острова', iso: 'MH'},
	MQ: {name: 'Мартиника', iso: 'MQ'},
	MR: {name: 'Мавритания', iso: 'MR'},
	MU: {name: 'Маврикий', iso: 'MU'},
	YT: {name: 'Майотта', iso: 'YT'},
	MX: {name: 'Мексика', iso: 'MX'},
	FM: {name: 'Микронезия', iso: 'FM'},
	MD: {name: 'Молдавия', iso: 'MD'},
	MC: {name: 'Монако', iso: 'MC'},
	MN: {name: 'Монголия', iso: 'MN'},
	ME: {name: 'Черногория', iso: 'ME'},
	MS: {name: 'Монтсеррат', iso: 'MS'},
	MA: {name: 'Марокко', iso: 'MA'},
	MZ: {name: 'Мозамбик', iso: 'MZ'},
	MM: {name: 'Мьянма', iso: 'MM'},
	NA: {name: 'Намибия', iso: 'NA'},
	NR: {name: 'Науру', iso: 'NR'},
	NP: {name: 'Непал', iso: 'NP'},
	NL: {name: 'Нидерланды', iso: 'NL'},
	NC: {name: 'Новая Каледония', iso: 'NC'},
	NZ: {name: 'Новая Зеландия', iso: 'NZ'},
	NI: {name: 'Никарагуа', iso: 'NI'},
	NE: {name: 'Нигер', iso: 'NE'},
	NG: {name: 'Нигерия', iso: 'NG'},
	NU: {name: 'Ниуэ', iso: 'NU'},
	NF: {name: 'Норфолк', iso: 'NF'},
	MP: {name: 'Северные Марианские острова', iso: 'MP'},
	NO: {name: 'Норвегия', iso: 'NO'},
	OM: {name: 'Оман', iso: 'OM'},
	PK: {name: 'Пакистан', iso: 'PK'},
	PW: {name: 'Палау', iso: 'PW'},
	PS: {name: 'Палестина', iso: 'PS'},
	PA: {name: 'Панама', iso: 'PA'},
	PG: {name: 'Папуа — Новая Гвинея', iso: 'PG'},
	PY: {name: 'Парагвай', iso: 'PY'},
	PE: {name: 'Перу', iso: 'PE'},
	PH: {name: 'Филиппины', iso: 'PH'},
	PN: {name: 'Острова Питкэрн', iso: 'PN'},
	PL: {name: 'Польша', iso: 'PL'},
	PT: {name: 'Португалия', iso: 'PT'},
	PR: {name: 'Пуэрто-Рико', iso: 'PR'},
	QA: {name: 'Катар', iso: 'QA'},
	RE: {name: 'Реюньон', iso: 'RE'},
	RO: {name: 'Румыния', iso: 'RO'},
	RU: {name: 'Россия', iso: 'RU'},
	RW: {name: 'Руанда', iso: 'RW'},
	BL: {name: 'Сен-Бартелеми', iso: 'BL'},
	SH: {name: 'Остров Святой Елены', iso: 'SH'},
	KN: {name: 'Сент-Китс и Невис', iso: 'KN'},
	LC: {name: 'Сент-Люсия', iso: 'LC'},
	MF: {name: 'Сен-Мартен', iso: 'MF'},
	PM: {name: 'Сен-Пьер и Микелон', iso: 'PM'},
	VC: {name: 'Сент-Винсент и Гренадины', iso: 'VC'},
	WS: {name: 'Самоа', iso: 'WS'},
	SM: {name: 'Сан-Марино', iso: 'SM'},
	ST: {name: 'Сан-Томе и Принсипи', iso: 'ST'},
	SA: {name: 'Саудовская Аравия', iso: 'SA'},
	SN: {name: 'Сенегал', iso: 'SN'},
	RS: {name: 'Сербия', iso: 'RS'},
	SC: {name: 'Сейшельские острова', iso: 'SC'},
	SL: {name: 'Сьерра-Леоне', iso: 'SL'},
	SG: {name: 'Сингапур', iso: 'SG'},
	SX: {name: 'Синт-Мартен', iso: 'SX'},
	SK: {name: 'Словакия', iso: 'SK'},
	SI: {name: 'Словения', iso: 'SI'},
	SB: {name: 'Соломоновы острова', iso: 'SB'},
	SO: {name: 'Сомали', iso: 'SO'},
	ZA: {name: 'Южно-Африканская Республика', iso: 'ZA'},
	GS: {name: 'Южная Георгия и Южные Сандвичевы острова', iso: 'GS'},
	SS: {name: 'Южный Судан', iso: 'SS'},
	ES: {name: 'Испания', iso: 'ES'},
	LK: {name: 'Шри-Ланка', iso: 'LK'},
	SD: {name: 'Судан', iso: 'SD'},
	SR: {name: 'Суринам', iso: 'SR'},
	SJ: {name: 'Шпицберген и Ян-Майен', iso: 'SJ'},
	SZ: {name: 'Свазиленд', iso: 'SZ'},
	SE: {name: 'Швеция', iso: 'SE'},
	CH: {name: 'Швейцария', iso: 'CH'},
	SY: {name: 'Сирия', iso: 'SY'},
	TW: {name: 'Тайвань', iso: 'TW'},
	TJ: {name: 'Таджикистан', iso: 'TJ'},
	TZ: {name: 'Танзания', iso: 'TZ'},
	TH: {name: 'Таиланд', iso: 'TH'},
	TL: {name: 'Восточный Тимор', iso: 'TL'},
	TG: {name: 'Того', iso: 'TG'},
	TK: {name: 'Токелау', iso: 'TK'},
	TO: {name: 'Тонга', iso: 'TO'},
	TT: {name: 'Тринидад и Тобаго', iso: 'TT'},
	TN: {name: 'Тунис', iso: 'TN'},
	TR: {name: 'Турция', iso: 'TR'},
	TM: {name: 'Туркмения', iso: 'TM'},
	TC: {name: 'Теркс и Кайкос', iso: 'TC'},
	TV: {name: 'Тувалу', iso: 'TV'},
	UG: {name: 'Уганда', iso: 'UG'},
	UA: {name: 'Украина', iso: 'UA'},
	AE: {name: 'Объединенные Арабские Эмираты', iso: 'AE'},
	GB: {name: 'Великобритания', iso: 'GB'},
	US: {name: 'Соединенные Штаты Америки', iso: 'US'},
	UM: {name: 'Малые Тихоокеанские отдаленные острова США', iso: 'UM'},
	UY: {name: 'Уругвай', iso: 'UY'},
	UZ: {name: 'Узбекистан', iso: 'UZ'},
	VU: {name: 'Вануату', iso: 'VU'},
	VE: {name: 'Венесуэла', iso: 'VE'},
	VN: {name: 'Вьетнам', iso: 'VN'},
	VG: {name: 'Виргинские острова (Великобритания)', iso: 'VG'},
	VI: {name: 'Виргинские острова (США)', iso: 'VI'},
	WF: {name: 'Уоллис и Футуна', iso: 'WF'},
	EH: {name: 'Западная Сахара', iso: 'EH'},
	YE: {name: 'Йемен', iso: 'YE'},
	ZM: {name: 'Замбия', iso: 'ZM'},
	ZW: {name: 'Зимбабве', iso: 'ZW'},
};

export const countriesArr = [
	{name: 'Афганистан', value: 'AF'},
	{name: 'Аландские острова', value: 'AX'},
	{name: 'Албания', value: 'AL'},
	{name: 'Алжир', value: 'DZ'},
	{name: 'Американское Самоа', value: 'AS'},
	{name: 'Андорра', value: 'AD'},
	{name: 'Ангола', value: 'AO'},
	{name: 'Ангилья', value: 'AI'},
	{name: 'Антарктика', value: 'AQ'},
	{name: 'Антигуа и Барбуда', value: 'AG'},
	{name: 'Аргентина', value: 'AR'},
	{name: 'Армения', value: 'AM'},
	{name: 'Аруба', value: 'AW'},
	{name: 'Австралия', value: 'AU'},
	{name: 'Австрия', value: 'AT'},
	{name: 'Азербайджан', value: 'AZ'},
	{name: 'Багамы', value: 'BS'},
	{name: 'Бахрейн', value: 'BH'},
	{name: 'Бангладеш', value: 'BD'},
	{name: 'Барбадос', value: 'BB'},
	{name: 'Беларусь', value: 'BY'},
	{name: 'Бельгия', value: 'BE'},
	{name: 'Белиз', value: 'BZ'},
	{name: 'Бенин', value: 'BJ'},
	{name: 'Бермудские острова', value: 'BM'},
	{name: 'Бутан', value: 'BT'},
	{name: 'Боливия', value: 'BO'},
	{name: 'Бонэйр, Синт-Эстатиус и Саба', value: 'BQ'},
	{name: 'Босния и Герцеговина', value: 'BA'},
	{name: 'Ботсвана', value: 'BW'},
	{name: 'Буве', value: 'BV'},
	{name: 'Бразилия', value: 'BR'},
	{name: 'Британская территория в Индийском океане', value: 'IO'},
	{name: 'Бруней', value: 'BN'},
	{name: 'Болгария', value: 'BG'},
	{name: 'Буркина-Фасо', value: 'BF'},
	{name: 'Бурунди', value: 'BI'},
	{name: 'Камбоджа', value: 'KH'},
	{name: 'Камерун', value: 'CM'},
	{name: 'Канада', value: 'CA'},
	{name: 'Кабо-Верде', value: 'CV'},
	{name: 'Каймановы острова', value: 'KY'},
	{name: 'Центральноафриканская Республика', value: 'CF'},
	{name: 'Чад', value: 'TD'},
	{name: 'Чили', value: 'CL'},
	{name: 'Китай', value: 'CN'},
	{name: 'Остров Рождества', value: 'CX'},
	{name: 'Кокосовые (Килинг) острова', value: 'CC'},
	{name: 'Колумбия', value: 'CO'},
	{name: 'Коморы', value: 'KM'},
	{name: 'Конго', value: 'CG'},
	{name: 'Конго (Демократическая Республика)', value: 'CD'},
	{name: 'Острова Кука', value: 'CK'},
	{name: 'Коста-Рика', value: 'CR'},
	{name: "Кот-д'Ивуар", value: 'CI'},
	{name: 'Хорватия', value: 'HR'},
	{name: 'Куба', value: 'CU'},
	{name: 'Кюрасао', value: 'CW'},
	{name: 'Кипр', value: 'CY'},
	{name: 'Чехия', value: 'CZ'},
	{name: 'Дания', value: 'DK'},
	{name: 'Джибути', value: 'DJ'},
	{name: 'Доминика', value: 'DM'},
	{name: 'Доминиканская Республика', value: 'DO'},
	{name: 'Эквадор', value: 'EC'},
	{name: 'Египет', value: 'EG'},
	{name: 'Сальвадор', value: 'SV'},
	{name: 'Экваториальная Гвинея', value: 'GQ'},
	{name: 'Эритрея', value: 'ER'},
	{name: 'Эстония', value: 'EE'},
	{name: 'Эфиопия', value: 'ET'},
	{name: 'Фолклендские (Мальвинские) острова', value: 'FK'},
	{name: 'Фарерские острова', value: 'FO'},
	{name: 'Фиджи', value: 'FJ'},
	{name: 'Финляндия', value: 'FI'},
	{name: 'Франция', value: 'FR'},
	{name: 'Французская Гвиана', value: 'GF'},
	{name: 'Французская Полинезия', value: 'PF'},
	{name: 'Французские Южные территории', value: 'TF'},
	{name: 'Габон', value: 'GA'},
	{name: 'Гамбия', value: 'GM'},
	{name: 'Грузия', value: 'GE'},
	{name: 'Германия', value: 'DE'},
	{name: 'Гана', value: 'GH'},
	{name: 'Гибралтар', value: 'GI'},
	{name: 'Греция', value: 'GR'},
	{name: 'Гренландия', value: 'GL'},
	{name: 'Гренада', value: 'GD'},
	{name: 'Гваделупа', value: 'GP'},
	{name: 'Гуам', value: 'GU'},
	{name: 'Гватемала', value: 'GT'},
	{name: 'Гернси', value: 'GG'},
	{name: 'Гвинея', value: 'GN'},
	{name: 'Гвинея-Бисау', value: 'GW'},
	{name: 'Гайана', value: 'GY'},
	{name: 'Гаити', value: 'HT'},
	{name: 'Остров Херд и острова Макдональд', value: 'HM'},
	{name: 'Ватикан', value: 'VA'},
	{name: 'Гондурас', value: 'HN'},
	{name: 'Гонконг', value: 'HK'},
	{name: 'Венгрия', value: 'HU'},
	{name: 'Исландия', value: 'IS'},
	{name: 'Индия', value: 'IN'},
	{name: 'Индонезия', value: 'ID'},
	{name: 'Иран', value: 'IR'},
	{name: 'Ирак', value: 'IQ'},
	{name: 'Ирландия', value: 'IE'},
	{name: 'Остров Мэн', value: 'IM'},
	{name: 'Израиль', value: 'IL'},
	{name: 'Италия', value: 'IT'},
	{name: 'Ямайка', value: 'JM'},
	{name: 'Япония', value: 'JP'},
	{name: 'Джерси', value: 'JE'},
	{name: 'Иордания', value: 'JO'},
	{name: 'Казахстан', value: 'KZ'},
	{name: 'Кения', value: 'KE'},
	{name: 'Кирибати', value: 'KI'},
	{name: 'Северная Корея', value: 'KP'},
	{name: 'Южная Корея', value: 'KR'},
	{name: 'Кувейт', value: 'KW'},
	{name: 'Киргизия', value: 'KG'},
	{name: 'Лаос', value: 'LA'},
	{name: 'Латвия', value: 'LV'},
	{name: 'Ливан', value: 'LB'},
	{name: 'Лесото', value: 'LS'},
	{name: 'Либерия', value: 'LR'},
	{name: 'Ливия', value: 'LY'},
	{name: 'Лихтенштейн', value: 'LI'},
	{name: 'Литва', value: 'LT'},
	{name: 'Люксембург', value: 'LU'},
	{name: 'Макао', value: 'MO'},
	{name: 'Македония', value: 'MK'},
	{name: 'Мадагаскар', value: 'MG'},
	{name: 'Малави', value: 'MW'},
	{name: 'Малайзия', value: 'MY'},
	{name: 'Мальдивы', value: 'MV'},
	{name: 'Мали', value: 'ML'},
	{name: 'Мальта', value: 'MT'},
	{name: 'Маршалловы острова', value: 'MH'},
	{name: 'Мартиника', value: 'MQ'},
	{name: 'Мавритания', value: 'MR'},
	{name: 'Маврикий', value: 'MU'},
	{name: 'Майотта', value: 'YT'},
	{name: 'Мексика', value: 'MX'},
	{name: 'Микронезия', value: 'FM'},
	{name: 'Молдавия', value: 'MD'},
	{name: 'Монако', value: 'MC'},
	{name: 'Монголия', value: 'MN'},
	{name: 'Черногория', value: 'ME'},
	{name: 'Монтсеррат', value: 'MS'},
	{name: 'Марокко', value: 'MA'},
	{name: 'Мозамбик', value: 'MZ'},
	{name: 'Мьянма', value: 'MM'},
	{name: 'Намибия', value: 'NA'},
	{name: 'Науру', value: 'NR'},
	{name: 'Непал', value: 'NP'},
	{name: 'Нидерланды', value: 'NL'},
	{name: 'Новая Каледония', value: 'NC'},
	{name: 'Новая Зеландия', value: 'NZ'},
	{name: 'Никарагуа', value: 'NI'},
	{name: 'Нигер', value: 'NE'},
	{name: 'Нигерия', value: 'NG'},
	{name: 'Ниуэ', value: 'NU'},
	{name: 'Норфолк', value: 'NF'},
	{name: 'Северные Марианские острова', value: 'MP'},
	{name: 'Норвегия', value: 'NO'},
	{name: 'Оман', value: 'OM'},
	{name: 'Пакистан', value: 'PK'},
	{name: 'Палау', value: 'PW'},
	{name: 'Палестина', value: 'PS'},
	{name: 'Панама', value: 'PA'},
	{name: 'Папуа — Новая Гвинея', value: 'PG'},
	{name: 'Парагвай', value: 'PY'},
	{name: 'Перу', value: 'PE'},
	{name: 'Филиппины', value: 'PH'},
	{name: 'Острова Питкэрн', value: 'PN'},
	{name: 'Польша', value: 'PL'},
	{name: 'Португалия', value: 'PT'},
	{name: 'Пуэрто-Рико', value: 'PR'},
	{name: 'Катар', value: 'QA'},
	{name: 'Реюньон', value: 'RE'},
	{name: 'Румыния', value: 'RO'},
	{name: 'Россия', value: 'RU'},
	{name: 'Руанда', value: 'RW'},
	{name: 'Сен-Бартелеми', value: 'BL'},
	{name: 'Остров Святой Елены', value: 'SH'},
	{name: 'Сент-Китс и Невис', value: 'KN'},
	{name: 'Сент-Люсия', value: 'LC'},
	{name: 'Сен-Мартен', value: 'MF'},
	{name: 'Сен-Пьер и Микелон', value: 'PM'},
	{name: 'Сент-Винсент и Гренадины', value: 'VC'},
	{name: 'Самоа', value: 'WS'},
	{name: 'Сан-Марино', value: 'SM'},
	{name: 'Сан-Томе и Принсипи', value: 'ST'},
	{name: 'Саудовская Аравия', value: 'SA'},
	{name: 'Сенегал', value: 'SN'},
	{name: 'Сербия', value: 'RS'},
	{name: 'Сейшельские острова', value: 'SC'},
	{name: 'Сьерра-Леоне', value: 'SL'},
	{name: 'Сингапур', value: 'SG'},
	{name: 'Синт-Мартен', value: 'SX'},
	{name: 'Словакия', value: 'SK'},
	{name: 'Словения', value: 'SI'},
	{name: 'Соломоновы острова', value: 'SB'},
	{name: 'Сомали', value: 'SO'},
	{name: 'Южно-Африканская Республика', value: 'ZA'},
	{name: 'Южная Георгия и Южные Сандвичевы острова', value: 'GS'},
	{name: 'Южный Судан', value: 'SS'},
	{name: 'Испания', value: 'ES'},
	{name: 'Шри-Ланка', value: 'LK'},
	{name: 'Судан', value: 'SD'},
	{name: 'Суринам', value: 'SR'},
	{name: 'Шпицберген и Ян-Майен', value: 'SJ'},
	{name: 'Свазиленд', value: 'SZ'},
	{name: 'Швеция', value: 'SE'},
	{name: 'Швейцария', value: 'CH'},
	{name: 'Сирия', value: 'SY'},
	{name: 'Тайвань', value: 'TW'},
	{name: 'Таджикистан', value: 'TJ'},
	{name: 'Танзания', value: 'TZ'},
	{name: 'Таиланд', value: 'TH'},
	{name: 'Восточный Тимор', value: 'TL'},
	{name: 'Того', value: 'TG'},
	{name: 'Токелау', value: 'TK'},
	{name: 'Тонга', value: 'TO'},
	{name: 'Тринидад и Тобаго', value: 'TT'},
	{name: 'Тунис', value: 'TN'},
	{name: 'Турция', value: 'TR'},
	{name: 'Туркмения', value: 'TM'},
	{name: 'Теркс и Кайкос', value: 'TC'},
	{name: 'Тувалу', value: 'TV'},
	{name: 'Уганда', value: 'UG'},
	{name: 'Украина', value: 'UA'},
	{name: 'Объединенные Арабские Эмираты', value: 'AE'},
	{name: 'Великобритания', value: 'GB'},
	{name: 'Соединенные Штаты Америки', value: 'US'},
	{name: 'Малые Тихоокеанские отдаленные острова США', value: 'UM'},
	{name: 'Уругвай', value: 'UY'},
	{name: 'Узбекистан', value: 'UZ'},
	{name: 'Вануату', value: 'VU'},
	{name: 'Венесуэла', value: 'VE'},
	{name: 'Вьетнам', value: 'VN'},
	{name: 'Виргинские острова (Великобритания)', value: 'VG'},
	{name: 'Виргинские острова (США)', value: 'VI'},
	{name: 'Уоллис и Футуна', value: 'WF'},
	{name: 'Западная Сахара', value: 'EH'},
	{name: 'Йемен', value: 'YE'},
	{name: 'Замбия', value: 'ZM'},
	{name: 'Зимбабве', value: 'ZW'},
];
