# Generated by Django 4.2.4 on 2023-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('путешествия', 'Путешествия'), ('развлечения', 'Развлечения'), ('развитие', 'Развитие')], max_length=50)),
                ('complexity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='goal_images/')),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('code', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
