# Generated by Django 4.2.4 on 2023-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0003_initial'),
        ('goals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='added_by_users',
            field=models.ManyToManyField(related_name='added_goals', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='goal',
            name='comments',
            field=models.ManyToManyField(related_name='goal_comments', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_by_users',
            field=models.ManyToManyField(related_name='completed_goals', to='users.customuser'),
        ),
    ]
