# Generated by Django 4.2.4 on 2023-08-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.CharField(
                choices=[
                    ("travel", "Путешествия"),
                    ("fun", "Развлечения"),
                    ("clever", "Развитие"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goal",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goals.category",
            ),
        ),
    ]
