# Generated by Django 4.2.4 on 2023-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_alter_category_name_alter_goal_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="complexity",
            field=models.CharField(
                choices=[("easy", "Легко"), ("medium", "Средне"), ("hard", "Тяжело")],
                max_length=20,
            ),
        ),
    ]
