# Generated by Django 4.2.4 on 2023-08-08 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0003_initial"),
        ("goals", "0005_alter_goal_complexity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="added_by_users",
            field=models.ManyToManyField(
                blank=True, related_name="added_goals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="goal_comments", to="comments.comment"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="completed_by_users",
            field=models.ManyToManyField(
                blank=True, related_name="completed_goals", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
