# Generated by Django 4.2.4 on 2023-08-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("goals", "0006_alter_goal_added_by_users_alter_goal_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="categories.category"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgoals",
                to="categories.category",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
