# Generated by Django 4.2.4 on 2023-08-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("goals", "0007_alter_goal_category_alter_goal_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="subgoals",
            field=models.ManyToManyField(
                blank=True, related_name="category_subgoals", to="goals.goal"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subgoals_goal",
                to="categories.category",
            ),
        ),
    ]
