# Generated by Django 4.2.3 on 2023-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_goal_subgoals_alter_goal_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='added_from_list',
            field=models.BooleanField(default=False),
        ),
    ]
