# Generated by Django 4.2.3 on 2024-01-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0009_goal_added_from_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='goal',
            name='added_from_list',
        ),
        migrations.AddField(
            model_name='goal',
            name='added_from_list',
            field=models.ManyToManyField(blank=True, related_name='added_from_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
