# Generated by Django 4.2.3 on 2024-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_alter_goal_added_from_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time_to_complete',
            field=models.DurationField(blank=True, choices=[(1, '1 час'), (24, '1 день'), (168, '1 неделя'), (720, '1 месяц')], null=True, verbose_name='Время на выполнение'),
        ),
    ]
