# Generated by Django 4.2.3 on 2024-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_goal_time_to_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='time_to_complete',
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
    ]
