# Generated by Django 4.2.3 on 2024-02-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
