# Generated by Django 4.2.3 on 2024-02-03 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0003_achievement_achieved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='achievement',
            name='unique_achievement_per_user',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieved',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achieved_users',
            field=models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
