import type {FriendsNewsEvent} from './FriendsNewsFeed';

export const mockFriendsNewsEvents: FriendsNewsEvent[] = [
	{
		id: '1',
		type: 'achievement',
		userId: 101,
		userName: 'Иван',
		achievementId: 25,
		achievementTitle: 'Ладно, и так сойдет...',
		achievementDescription: 'Создайте свою первую цель',
		createdAt: '2026-02-09T10:15:00Z',
		likesCount: 12,
		likedByMe: false,
	},
	{
		id: '2',
		type: 'level_up',
		userId: 102,
		userName: 'Мария',
		level: 5,
		createdAt: '2026-02-09T12:30:00Z',
		likesCount: 8,
		likedByMe: true,
	},
	{
		id: '3',
		type: 'streak',
		userId: 101,
		userName: 'Иван',
		streakDays: 7,
		createdAt: '2026-02-08T09:00:00Z',
		likesCount: 5,
		likedByMe: false,
	},
	{
		id: '4',
		type: 'return_after_pause',
		userId: 103,
		userName: 'Мария',
		listId: 501,
		listName: 'Книги 2026',
		pauseDays: 30,
		createdAt: '2026-02-07T18:45:00Z',
		likesCount: 3,
		likedByMe: false,
	},
	{
		id: '5',
		type: 'list_completed',
		userId: 104,
		userName: 'Иван',
		listId: 600,
		listName: '100 целей',
		createdAt: '2026-02-06T14:20:00Z',
		likesCount: 21,
		likedByMe: true,
	},
	{
		id: '6',
		type: 'goal_taken_from_your_list',
		userId: 105,
		userName: 'Мария',
		sourceUserId: 1,
		sourceGoalId: 700,
		sourceGoalTitle: 'Прыгнуть с парашутом',
		createdAt: '2026-02-06T11:05:00Z',
		likesCount: 9,
		likedByMe: false,
	},
	{
		id: '7',
		type: 'popular_goal_completed',
		userId: 106,
		userName: 'Иван',
		goalId: 800,
		goalTitle: 'Пробежать марафон',
		friendsWithSameGoalCount: 3,
		createdAt: '2026-02-05T19:40:00Z',
		likesCount: 14,
		likedByMe: false,
	},
	{
		id: '8',
		type: 'daily_stats',
		userId: 107,
		userName: 'Иван',
		goalsCount: 5,
		listsCount: 1,
		completedGoals: ['Пробежать 5 км', 'Выучить 20 слов', 'Позвонить родителям', 'Прочитать 30 страниц', 'Сделать зарядку'],
		completedLists: ['Список «День 09.02»'],
		createdAt: '2026-02-05T07:30:00Z',
		likesCount: 4,
		likedByMe: false,
	},
	{
		id: '9',
		type: 'weekly_leader',
		userId: 108,
		userName: 'Иван',
		placeInLeaders: 1,
		createdAt: '2026-02-04T10:00:00Z',
		likesCount: 18,
		likedByMe: false,
	},
	// событие текущего пользователя
	{
		id: 'current-user-weekly-leader',
		type: 'weekly_leader',
		userId: 1,
		userName: 'Вы',
		placeInLeaders: 2,
		createdAt: '2026-02-04T10:00:00Z',
		likesCount: 5,
		// свои события всегда отображаются как уже отмеченные
		likedByMe: true,
		// флаг, который используется для особого оформления и блокировки лайка
		isOwn: true,
	},
];
