# Generated by Django 4.2.4 on 2023-11-05 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "comments",
            "0004_comment_date_created_comment_dislikes_comment_likes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AlterField(
            model_name="comment",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="comment_photos/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
