# Generated by Django 4.2.4 on 2023-11-09 18:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0007_userprofile_commentaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="photos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(upload_to="comment_photos/"),
                blank=True,
                null=True,
                size=10,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
