# Generated by Django 4.2.4 on 2023-11-09 18:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0008_alter_comment_photos_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="photos",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
