# Generated by Django 4.2.4 on 2023-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0010_remove_comment_photos_commentphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="comment_photos", to="comments.commentphoto"
            ),
        ),
    ]
