# Generated by Django 4.2.3 on 2023-11-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_comment_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentphoto',
            options={'verbose_name': 'Comment Photo', 'verbose_name_plural': 'Comment Photos'},
        ),
    ]
