# Generated by Django 4.2.3 on 2025-02-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_alter_commentphoto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photos',
        ),
        migrations.AlterField(
            model_name='commentphoto',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='comments.comment'),
        ),
    ]
