# Generated by Django 4.2.3 on 2024-02-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_achievement_unique_achievement_per_user_and_more'),
        ('users', '0005_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements_received',
            field=models.ManyToManyField(blank=True, related_name='received_by_users', to='achievements.achievement'),
        ),
    ]
